version: '3.8'

services:
  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:3000" # Проброс порта для клиентской части, если требуется

  server:
    build:
      context: ./server
    ports:
      - "8080:3000" # Проброс порта для серверной части
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
